### PR TITLE
Feat linking

### PR DESCRIPTION
**Pull request by jlgnava1986**
Created contact page and linked home, about and contact pages.

### CODE REVIEW

**Comment by jlgnava1986** [comment]
image

Dropdown is working with placeholders.

**Comment by jlgnava1986** [comment]
[Dev Training | Controller, Links and Include](https://trello.com/c/rPuXdOTV/932-dev-training-controller-links-and-include)

**Comment by jlgnava1986** [comment]
[Dev Training | Controller, Links and Include](https://trello.com/c/rPuXdOTV/932-dev-training-controller-links-and-include)

**Comment by nressa** [comment]
@jlgnava1986 please resolve the conflicting files.
Example Steps:
1. On your local branch pull origin develop
2. Conflicting files will be shown. Visit every conflicting files and pick the version you want to be saved.
3. Commit changes after removing conflicting files
4. Push your new commit.

Please inform me after solving the conflict.

**Comment by jlgnava1986** [comment]
[Dev Training | Solve Git Conflict](https://trello.com/c/5T3sRw4h/941-dev-training-solve-git-conflict)

**Pull request merged**
